name: CI

on:
  pull_request:
    paths:
      - ".github/workflows/**"

jobs:
  lint-workflows:
    name: Lint Workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: devops-actions/actionlint@9fb9c192862f19e684586ca84b500461bcd8a541 # v0.1.12
